#!/bin/sh

echo Downloading Qt
wget -c --no-check-certificate -nv https://download.qt.io/archive/qt/5.7/5.7.0/qt-opensource-linux-x64-android-5.7.0.run
echo Installing Qt
extract-qt-installer qt-opensource-linux-x64-android-5.7.0.run $PWD/Qt
install-android-sdk platform-tool,build-tools-22.0.1,android-23

echo Create qt.env
cat << EOF > qt.env
export QT_ROOT=$PWD/Qt
export QT_HOME=$PWD/Qt/5.7
export PATH=$PWD/Qt/5.7/android_armv7/bin:$PWD/android-sdk-linux/tools:$PATH
export ANDROID_NDK_ROOT=$PWD/android-ndk-r10c
export ANDROID_SDK_ROOT=$PWD/android-sdk-linux
EOF
